### ISSUE TITLE
[FEATURE] - Add responsive view to the homepage

### ISSUE THREAD

**Issue by creative-tutorials** [creative-tutorials/hashtag#22]
# Task
- [ ] Add a responsive view to fit both mobile & PC devices
- [ ] Remove Sidebar on mobile responsive and replace it with a **header**
- [ ] You can change the theme if you'd like but themes must be reviewed first before shipment

![1666095921777](https://user-images.githubusercontent.com/68476321/196429244-9dedb0e5-81a7-497b-901c-ba079b784f96.png)

**Comment by avezqureshi14** [comment]
Please can you assign this task to me

**Comment by creative-tutorials** [comment]
> Please can you assign this task to me

# Okay but make sure to read 👉 [Contribution Guidelines](https://github.com/creative-tutorials/hashtag/blob/master/CONTRIBUTING.md) 👈

**Comment by creative-tutorials** [comment]
@avezqureshi14 Hi are you working on the issue

**Comment by creative-tutorials** [comment]
@avezqureshi14 if the issue is not worked on in the next 14 hours I'm afraid I'll assign it to someone

**Comment by avezqureshi14** [comment]
yeah @creative-tutorials  i m ready to do this, Sorry for replying later

**Comment by creative-tutorials** [comment]
> yeah @creative-tutorials  i m ready to do this, Sorry for replying later and I had even started working on this issue

Okay you've been assigned to the issue #22

**Comment by avezqureshi14** [comment]
Sir when I tried running this site in my local it is showing numerous errors and I even tried to debug them but most them are kept occuring

**Comment by creative-tutorials** [comment]
> Sir when I tried running this site in my local it is showing numerous errors and I even tried to debug them but most them are kept occuring 

Some errors are caused by issue fetching the data from the API, can you screenshot the error it's showing

**Comment by creative-tutorials** [comment]
@avezqureshi14 are you still facing issues
