### ISSUE TITLE
[FEATURE] - Change the UI the way you like

### ISSUE THREAD

**Issue by creative-tutorials** [creative-tutorials/hashtag#25]
**Change the UI**
I recently I'm using an old UI. I need a change

**Screenshot**
![1666095921777](https://user-images.githubusercontent.com/68476321/196429244-9dedb0e5-81a7-497b-901c-ba079b784f96.png)

**Task**
- [ ] Pick your colour
- [ ] merge them and create a beautiful UI out of it
- [ ] Change the colours on all pages too

**Additional context**
To view pages, you can fork the repo and route between the pages listed below

- login
- sign-up

and many more

To see the list of available routes visit the [route file](https://github.com/creative-tutorials/hashtag/blob/master/src/App.tsx)

**Comment by satyamrs00** [comment]
hey i want to work on this one 
can you assign this to me ?

**Comment by creative-tutorials** [comment]
> hey I want to work on this one can you assign this to me?

Okay, I'll do that 

> hey i want to work on this one can you assign this to me ?

Okay I'll do that right away

**Comment by creative-tutorials** [comment]
@satyamrs00 Now you can start working on it 😌🥳👍🤪

**Comment by creative-tutorials** [comment]
@satyamrs00 also please don't forget to follow the [contribution guidelines](https://github.com/creative-tutorials/hashtag/blob/master/CONTRIBUTING.md)

**Comment by creative-tutorials** [comment]
@satyamrs00 any update on the issue

**Comment by satyamrs00** [comment]
its almost done now 
will open a pr by tomorrow

**Comment by creative-tutorials** [comment]
@satyamrs00 Okay Thanks for the update, have a great day ahead

**Comment by satyamrs00** [comment]
@creative-tutorials I won't be able to do it.
Sorry for your time wasted.

**Comment by creative-tutorials** [comment]
@satyamrs00 No problem
